### ISSUE TITLE
[EPIC] Redesign the modeling module with DataFusion and Rust

### ISSUE THREAD

**Issue by goldmedal** [Canner/wren-engine#589]
# Description
Our goal is redesigning the modeling part of Wren Engine using DataFusion. Make it be more portable and composable. With DataFusion at the helm, we expect to deliver full SQL support an query planning.

# Todo Lists
- [ ]  Model
    - [x]  TableReference https://github.com/Canner/wren-engine/pull/570
    - [ ]  ~ReferSql~
    - [x] https://github.com/Canner/wren-engine/issues/591
- [x]  Column
    - [x]  Expression https://github.com/Canner/wren-engine/pull/570
    - [x]  Calculated Field
- [x]  Relationship
    - [x]  MDL Lineage https://github.com/Canner/wren-engine/pull/588
    - [x]  Relationship Column #595
    - [x]  Used by Calculated Field
        - [x]  TO_ONE #595 #613 
        - [x]  TO_MANY
        - [x] Use the calculated field in another related model https://github.com/Canner/wren-engine/pull/676
- [x]  View
    - [x]  Query View https://github.com/Canner/wren-engine/pull/645
    - [x]  Cycling View Check https://github.com/Canner/wren-engine/pull/645
- [ ]  ~Macro (https://docs.rs/minijinja/latest/minijinja/)~
- [x]  Python API (PyO3)
    - [x]  https://github.com/Canner/wren-engine/pull/614
- [x]  CI workflow (We can follow how DataFusion do it)
    - [x]  Cargo Build Test
    - [x]  Unit test
    - [x]  Cargo fmt check
    - [x]  Cargo clippy check
    - [x] e2e test https://github.com/Canner/wren-engine/pull/604
- [x] type enhancement https://github.com/Canner/wren-engine/issues/590

**Comment by goldmedal** [comment]
All tickets have been finished. The beta version will be released soon.
